FROM node:18 as deps
WORKDIR /workspace
COPY SolConnectApp/package.json SolConnectApp/
RUN cd SolConnectApp && npm install

FROM rust:1.81
WORKDIR /workspace
COPY . .
RUN cargo build --workspace
CMD ["bash"]
