FROM rust:1.81.0-slim

# Install system deps UniFFI might need
RUN apt-get update && apt-get install -y \
    libssl-dev clang cmake pkg-config protobuf-compiler

# Install uniffi CLI
RUN cargo install uniffi-cli --version 0.29.2

WORKDIR /usr/src/solconnect

COPY . .

# Drop into a shell in the SDK directory
WORKDIR /usr/src/solconnect/mobile/solchat_sdk
CMD ["/bin/bash"] 