apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: solconnect-devnet
servers: 1
agents: 0
kubeAPI:
  host: "0.0.0.0"
  hostIP: "127.0.0.1"
  hostPort: "6550"
image: rancher/k3s:v1.28.8-k3s1
network: "solconnect-net"
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
env:
  - envVar: K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    nodeFilters:
      - server:*
options:
  k3d:
    wait: true
    timeout: "300s"
    disableLoadbalancer: false
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=servicelb
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
registries:
  use:
    - k3d-solconnect-registry:5000
  config: |
    mirrors:
      docker.io:
        endpoint:
          - https://registry-1.docker.io 