apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: solconnect-devnet
servers: 1
agents: 0
image: rancher/k3s:v1.28.8-k3s1
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "300s"
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
registries:
  create:
    name: k3d-solconnect-registry
    host: "localhost"
    hostPort: "5000"
