apiVersion: apps/v1
kind: Deployment
metadata:
  name: solconnect-relay
  labels:
    app: solconnect-relay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solconnect-relay
  template:
    metadata:
      labels:
        app: solconnect-relay
    spec:
      containers:
        - name: relay
          image: ghcr.io/astraldrift/solconnect:latest
          ports:
            - containerPort: 8080
          env:
            - name: RUST_LOG
              value: info
