name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test --workspace

  mobile-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: |
          cd apps/solchat_mobile
          npm install
          npm run lint
          npm run type-check
          npm test

  docker-build:
    runs-on: ubuntu-latest
    needs: [rust-tests, mobile-app]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: solconnect/relay:ci

  devnet-sim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - name: Create cluster
        run: k3d cluster create solconnect-devnet --config infra/devnet-k3d.yaml
      - name: Deploy relay example
        run: kubectl create deployment relay --image=solconnect/relay:ci --dry-run=client -o yaml
      - name: Cleanup
        run: k3d cluster delete solconnect-devnet
